platform :ios, '8.0'
use_frameworks!

target 'RxSocialConnect' do
    pod 'OAuthSwift', '~> 0.5.0'
    pod 'RxSwift', '~> 2.5.0'
    pod 'RxBlocking', '~> 2.5.0'
    
    pod 'Alamofire', '~> 3.0'
    
    pod 'Moya', '~> 6.5.0'
    pod 'Moya/RxSwift', '~> 6.5.0'
end

target 'RxSocialConnectTests' do
    pod 'Nimble', '~> 4.0.0'
    pod 'RxTests', '~> 2.5'
end